version: "3.8"

networks:
  thmar-apps:
    driver: bridge

volumes:
  pgadmin:
  db-data:
  odoo-web-data:

services:
  pg-db:
    image: postgres:15
    container_name: pg-db
    environment:
      - POSTGRES_USER=odoo19
      - POSTGRES_PASSWORD=odoo19
    ports:
      - "5433:5432"
    networks:
      - thmar-apps
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    networks:
      - thmar-apps
    volumes:
      - pgadmin:/var/lib/pgadmin

  odoo:
    image: odoo:19.0
    container_name: odoo
    depends_on:
      - pg-db
    ports:
      - "8019:8069"
      - "8072:8072"
    environment:
      HOST: pg-db
    volumes:
      # Mirror Odoo config
      - /root/odoo19/thmar_dani/docker/server/odoo_e/etc/:/etc/odoo/
      # Optional: Mount addons if needed
      - /root/odoo19/enterprise-19.0:/mnt/enterprise_addons
      - /root/odoo19/thamar_dani/thamar_purchase_custom:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    networks:
      - thmar-apps
    restart: always
